version: '3'

services: 
  frontend:
    image: node:10
    volumes:
      - ./frontend:/usr/src/app
    working_dir: /usr/src/app
    command: npm start
    ports:
      - 3000:3000
      - 45253:45253

  backend:
    image: node:10
    volumes:
      - ./backend:/usr/src/app
    working_dir: /usr/src/app
    environment: 
      - NODE_URI=0.0.0.0
    command: npm start
    ports:
      - 3001:3001
    
  db:
    image: postgres:latest
    environment: 
      - POSTGRES_DB=tpjdb
      - POSTGRES_PASSWORD=lorem
    volumes: 
      - ./backend/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    depends_on:
      - backend